#  Cloud Build เป็นบริการ CI/CD (Continuous Integration / Continuous Delivery) ของ Google Cloud ที่ช่วยให้เราสร้าง Pipeline สำหรับกระบวนการ Build, Test, และ Deploy ได้อย่างอัตโนมัติ
# ไฟล์ cloudbuild.yaml จะทำหน้าที่เป็นตัวกำหนดลำดับ “ขั้นตอนการทำงาน (Pipeline)” ต่าง ๆ
# เมื่อมีการ Trigger (เช่น Push โค้ดใหม่ขึ้น Git) ระบบจะรัน Pipeline ตามที่กำหนดไว้ในไฟล์นี้
steps:
  # reservations
  - name: 'gcr.io/cloud-builders/docker' # This is the name of the builder
    # args คือ คำสั่งที่จะใช้ในการ build โปรเจค
    args: [
        'build', # build คือ คำสั่งที่ใช้ในการ build โปรเจค
        '-t', # -t คือ คำสั่งที่ใช้ในการ tag โปรเจค
        'asia-southeast1-docker.pkg.dev/mailer-450009/reservations/production', # ชื่อ image ที่จะใช้ในการ push ไปที่ Container Registry
        '-f', # -f คือ คำสั่งที่ใช้ในการระบุ path ของ Dockerfile
        'apps/reservations/Dockerfile', # ชื่อไฟล์ Dockerfile ที่จะใช้ในการ build โปรเจค
        '.', # . คือ คำสั่งที่ใช้ในการระบุ path ของโปรเจค
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        # คำสั่ง "docker push" ใช้ในการ Push Image ขึ้นไปยัง Registry
        'push',

        # ชื่อ Image ที่ถูกสร้างในขั้นตอนก่อนหน้า
        'asia-southeast1-docker.pkg.dev/mailer-450009/reservations/production',
      ]

  # auth
  ###############################################################
  # ขั้นตอนที่ 1: ใช้ Cloud Builder ของ Docker เพื่อ Build Image
  ###############################################################
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        # คำสั่ง "docker build" ใช้ในการ Build Image
        'build',

        # ใช้ -t กำหนด Tag ของ Image ที่จะสร้าง
        # "asia-southeast1-docker.pkg.dev/mailer-450009/auth/production"
        # คือชื่อ Image ใน Google Artifact / Container Registry
        '-t',
        'asia-southeast1-docker.pkg.dev/mailer-450009/auth/production',

        # ใช้ -f ระบุ Dockerfile ที่จะใช้ build
        # ซึ่งอยู่ที่ "apps/auth/Dockerfile"
        '-f',
        'apps/auth/Dockerfile',

        # จุด '.' คือ build context
        # ระบุว่าให้ใช้โฟลเดอร์ปัจจุบัน (root) เป็น context
        # ในการส่งไฟล์ทั้งหมดให้ docker build
        '.',
      ]
  ###############################################################
  # ขั้นตอนที่ 2: Push Image ขึ้นไปยัง Registry
  ###############################################################
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        # คำสั่ง "docker push" สำหรับอัปโหลด Image เข้า Registry
        'push',

        # ชื่อ Image ที่ถูกสร้างในขั้นตอนก่อนหน้า
        'asia-southeast1-docker.pkg.dev/mailer-450009/auth/production',
      ]

  # notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/mailer-450009/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/mailer-450009/notifications/production',
      ]

  # payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/mailer-450009/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/mailer-450009/payments/production',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
# options.logging: CLOUD_LOGGING_ONLY เป็นการกำหนดรูปแบบการเก็บ Log ของ Cloud Build ให้บันทึกเฉพาะใน Cloud Logging (ชื่อเดิมคือ Stackdriver Logging) เท่านั้น โดยจะ ไม่ บันทึก Log ลงใน Google Cloud Storage (GCS)

# ไฟล์ cloudbuild.yaml นี้กำลังบอก Cloud Build ให้ อ่าน Dockerfile ในโฟลเดอร์ apps/reservations, สร้าง Image, ตั้ง Tag, แล้ว Push Image ไปยัง Registry ตามที่กำหนดไว้นั่นเองครับ
