services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - db

  reservations:
    image: asia-southeast1-docker.pkg.dev/mailer-450009/reservations/production
    ports:
      - '3000:3000'
    env_file:
      - ../apps/reservations/.env

  auth:
    image: asia-southeast1-docker.pkg.dev/mailer-450009/auth/production
    ports:
      - '3001:3001'
    env_file:
      - ../apps/auth/.env

  payments:
    image: asia-southeast1-docker.pkg.dev/mailer-450009/payments/production
    env_file:
      - ../apps/payments/.env

  notifications:
    image: asia-southeast1-docker.pkg.dev/mailer-450009/notifications/production
    env_file:
      - ../apps/notifications/.env

  db:
    image: mongo
